In [6]:
import numpy as np
import pandas as pd

In [7]:
pd.__version__

'1.4.2'

In [8]:
np.__version__

'1.21.5'

In [9]:
def hinge_loss_full(feature_matrix, labels, theta):
    """
    Finds the total hinge loss on a set of data given specific classification
    parameters.

    Args:
        feature_matrix - A numpy matrix describing the given data. Each row
            represents a single data point.
        labels - A numpy array where the kth element of the array is the
            correct classification of the kth row of the feature matrix.
        theta - A numpy array describing the linear classifier.
        theta_0 - A real valued number representing the offset parameter.


    Returns: A real number representing the hinge loss associated with the
    given dataset and parameters. This number should be the average hinge
    loss across all of the points in the feature matrix.
    """
    num_data_points = feature_matrix.shape[0]
    less_than_zero = np.maximum(np.zeros(num_data_points), 1 - labels * (np.dot(feature_matrix, theta)))
    hinge_loss = np.sum(less_than_zero)/num_data_points
    return hinge_loss

In [10]:
feature_matrix = np.array([[1,0,1],[1,1,1],[1,1,-1],[-1,1,1]])

In [11]:
feature_matrix.shape[0]

4

In [12]:
labels = np.array([2, 2.7, -0.7, 2])
labels

array([ 2. ,  2.7, -0.7,  2. ])

In [13]:
theta = [0, 1, 2]

In [14]:
hinge_loss_full(feature_matrix, labels, theta)

0.07500000000000001

In [15]:
np.dot(feature_matrix,theta)

array([ 2,  3, -1,  3])

In [16]:
z_values = labels - np.dot(feature_matrix, theta)

In [17]:
z_values

array([ 0. , -0.3,  0.3, -1. ])

In [18]:
np.sum(1 - z_values) / 4

1.25

In [19]:
# Compute Squared Loss
squared_loss = np.square(z_values)/2
squared_loss

array([0.   , 0.045, 0.045, 0.5  ])

In [20]:
np.sum(squared_loss) / 4

0.1475

In [21]:
import scikit-learn

SyntaxError: invalid syntax (464634962.py, line 1)

ModuleNotFoundError: No module named 'scikitlearn'

In [24]:
from sklearn import metrics

In [25]:
metrics.pairwise.rbf_kernel(X, Y=None, gamma=None)

NameError: name 'X' is not defined

In [31]:
X = np.array([[1,0,0]])
Y = np.array([[0,1,0]])

In [32]:
X

array([[1, 0, 0]])

In [33]:
Y

array([[0, 1, 0]])

In [34]:
metrics.pairwise.rbf_kernel(X.T, Y.T)

array([[0.36787944, 1.        , 0.36787944],
       [1.        , 0.36787944, 1.        ],
       [1.        , 0.36787944, 1.        ]])

In [35]:
from numpy import linalg as LA

In [38]:
np.square(LA.norm(X-Y))

2.0000000000000004